import { createFileRoute } from '@tanstack/react-router'

export const Route = createFileRoute('/ai-rating')({ component: AIRating })

function AIRating() {
  return (
    <div className="wrap">
      <div className="page-header">
        <h1>AI Rating System</h1>
        <p className="page-sub">How sessions are scored and what the numbers mean</p>
      </div>
      <div className="about-content">
        <p>
          Every session is rated by an AI model across five dimensions, each scored 1&ndash;10.
          These are combined using a weighted average to produce an aggregate rating (rounded to a
          whole number). The ratings are opinionated and designed to help surface interesting
          sessions &mdash; they are not official or authoritative.
        </p>
        <p>
          Price is intentionally excluded from the rating. It&rsquo;s shown in the table so you can
          make your own value judgment &mdash; what&rsquo;s worth it depends on your budget and what
          seats you&rsquo;re looking at.
        </p>

        <h2>Dimensions &amp; Weights</h2>

        <div className="rating-dimension">
          <h3>
            Significance <span className="rating-weight">30%</span>
          </h3>
          <p>
            How important is this session in the context of Olympic competition? Gold medal finals
            score highest, followed by other medal matches and semifinals. Sport popularity matters
            &mdash; a basketball final carries more global weight than a niche sport final. Sessions
            with multiple medal events get a significant boost since you&rsquo;re witnessing more
            history in a single sitting.
          </p>
        </div>

        <div className="rating-dimension">
          <h3>
            Experience <span className="rating-weight">25%</span>
          </h3>
          <p>
            How good will it be to watch live? This combines sport watchability with venue quality,
            but contextually &mdash; an iconic venue hosting a gold medal final scores much higher
            than the same venue hosting an early-round qualification. Evening sessions get a small
            boost, but only for high-energy sports where the crowd atmosphere genuinely changes
            after dark.
          </p>
        </div>

        <div className="rating-dimension">
          <h3>
            Star Power <span className="rating-weight">15%</span>
          </h3>
          <p>
            How likely are you to see globally recognized athletes? Sports like basketball,
            gymnastics, track &amp; field, and tennis have higher base star power. Later rounds
            guarantee top athletes are competing, while preliminary heats may not feature the
            biggest names in every matchup.
          </p>
        </div>

        <div className="rating-dimension">
          <h3>
            Uniqueness <span className="rating-weight">15%</span>
          </h3>
          <p>
            How rare or special is this opportunity? New and returning Olympic sports (flag
            football, lacrosse, cricket, squash, baseball, 3x3 basketball) get a bonus that scales
            with round importance &mdash; a flag football gold medal is more unique than pool play.
            Iconic venue pairings (baseball at Dodger Stadium, athletics at the Coliseum, surfing at
            Trestles) only boost uniqueness for meaningful rounds.
          </p>
        </div>

        <div className="rating-dimension">
          <h3>
            Demand <span className="rating-weight">15%</span>
          </h3>
          <p>
            How sought-after will this session be? This estimates how hard tickets will be to get
            based on sport popularity (especially in a US host city), round type, and price ceiling
            as a market signal. Cultural moment events &mdash; ceremonies, the 100m final,
            gymnastics all-around, USA basketball &mdash; get an additional boost. Baseball at
            Dodger Stadium rates maximum demand.
          </p>
        </div>

        <h2>Reading the Scores</h2>
        <ul>
          <li>
            <strong className="rating-great-text">8&ndash;10</strong> &mdash; Exceptional sessions
            you should strongly consider
          </li>
          <li>
            <strong className="rating-good-text">6&ndash;7</strong> &mdash; Strong sessions with
            good overall appeal
          </li>
          <li>
            <strong className="rating-fair-text">4&ndash;5</strong> &mdash; Decent sessions, solid
            if you&rsquo;re interested in the sport
          </li>
          <li>
            <strong className="rating-low-text">1&ndash;3</strong> &mdash; Early rounds or niche
            sports, still Olympic experiences
          </li>
        </ul>

        <h2>Limitations</h2>
        <p>
          These ratings are generated by AI based on general knowledge about Olympic sports, venue
          significance, and historical patterns. They don&rsquo;t account for personal preferences,
          specific matchups, your travel logistics, or real-time changes to schedules and pricing.
          Use them as a starting point, not a definitive guide.
        </p>
      </div>
      <div className="footer-note">
        Ratings generated with Claude &middot; Methodology designed for LA28 2028
      </div>
    </div>
  )
}
